version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: elasticblog-mysql
      working_dir: /application
      volumes:
        - .:/application
        - my-datavolume:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=elasticblog
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - "8082:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: elasticblog-elasticsearch
      volumes:
        - data01:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"

    webserver:
      image: nginx:alpine
      container_name: elasticblog-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: elasticblog-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

volumes:
  my-datavolume:
  data01:
    driver: local
